#!/bin/sh

set -eu

virtio_drm_present() {
  for card in /sys/class/drm/card[0-9]*; do
    [ -L "$card/device/driver" ] || continue
    driver=$(readlink "$card/device/driver") || continue
    [ "${driver##*/}" = virtio-pci ] && return 0
  done
  return 1
}

if virtio_drm_present; then
  export KWIN_DRM_NO_AMS=1
fi

exec /usr/bin/kwin_wayland_wrapper "$@"
