Window.SetBackgroundTopColor(0.043, 0.071, 0.125);
Window.SetBackgroundBottomColor(0.094, 0.216, 0.373);

logo.image = Image("lc300a-mark.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() * 0.34 - logo.image.GetHeight() / 2);

title.image = Image.Text("LC300A", 0.957, 0.969, 0.984);
title.sprite = Sprite(title.image);
title.sprite.SetX(Window.GetWidth() / 2 - title.image.GetWidth() / 2);
title.sprite.SetY(Window.GetHeight() * 0.57 - title.image.GetHeight() / 2);

subtitle.image = Image.Text("LUOCHUAN OS 300", 0.718, 0.769, 0.839);
subtitle.sprite = Sprite(subtitle.image);
subtitle.sprite.SetX(Window.GetWidth() / 2 - subtitle.image.GetWidth() / 2);
subtitle.sprite.SetY(Window.GetHeight() * 0.62 - subtitle.image.GetHeight() / 2);

indicator.image = Image.Text("STARTING", 0.37, 0.82, 0.85);
indicator.sprite = Sprite(indicator.image);
indicator.sprite.SetX(Window.GetWidth() / 2 - indicator.image.GetWidth() / 2);
indicator.sprite.SetY(Window.GetHeight() * 0.72 - indicator.image.GetHeight() / 2);
indicator.opacity_angle = 0;

fun refresh_callback()
{
    indicator.opacity_angle += ((2 * 3.14) / 50) * 0.75;
    minimum_opacity = 0.35;
    opacity = (Math.Cos(indicator.opacity_angle) + 1) / 2;
    opacity *= 1 - minimum_opacity;
    opacity += minimum_opacity;
    indicator.sprite.SetOpacity(opacity);
}

Plymouth.SetRefreshFunction(refresh_callback);
